vm:
  hosts:
    docker01:
      ansible_host: 192.168.100.150
      ansible_user: "root"
      ansible_python_interpreter: /usr/bin/python3.8
    docker02:
      ansible_host: 192.168.100.152
      ansible_user: "root"
      ansible_python_interpreter: /usr/bin/python3.8
