services:
  devcontainer:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
      - ~/.ssh:/root/.ssh:ro
      # Optional: Nur hinzufügen, wenn das Verzeichnis existiert
      # - ~/homelab-config:/workspace/live-config:cached
    environment:
      - TZ=Europe/Berlin
    command: sleep infinity
    # Wichtig: Container muss privilegiert sein für Docker-in-Docker
    privileged: true
    
  plantuml:
    image: plantuml/plantuml-server:latest
    ports:
      - "8080:8080"
    environment:
      - PLANTUML_LIMIT_SIZE=8192
    restart: unless-stopped

  excalidraw:
    image: excalidraw/excalidraw:latest
    ports:
      - "3000:80"
    restart: unless-stopped