services:
  coredns:
    image: coredns/coredns:1.12.0
    container_name: coredns
    command: -conf /etc/coredns/Corefile -dns.port 53
    restart: unless-stopped
    ports:
      - "5354:53/udp"
      - "5354:53/tcp"
      - "8081:8080"
    volumes:
      - ./Corefile:/etc/coredns/Corefile
      - ./internal-domain.db:/etc/coredns/internal-domain.db
