---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-test
  labels:
    app: nginx-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-test
  template:
    metadata:
      labels:
        app: nginx-test
    spec:
      containers:
        - name: nginx
          image: nginx:stable
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-test
spec:
  type: LoadBalancer
  # Optional: Feste IP anfordern
  # loadBalancerIP: 10.x.x.50  # Hier deine gewünschte statische IP eintragen
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app: nginx-test
